language: node_js
node_js:
  - "0.11"
  - "0.10"
install:
  - curl -L -O https://github.com/purescript/purescript/releases/download/v0.6.2/linux64.tar.gz
  - tar xvf linux64.tar.gz
  - export PATH=`pwd`/purescript:$PATH
  - npm install
  - bower update
